# Generated by Django 4.1.2 on 2022-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adress',
            field=models.TextField(default='dab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullName',
            field=models.TextField(default='dab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
