# Generated by Django 4.1.2 on 2022-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_manafacturer_product_producttype_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isAdvertisement',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
