# Generated by Django 4.1.2 on 2022-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_likedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='datePurchase',
        ),
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
